webpackJsonp(["common"],{

/***/ "../../../../../src/$$_gendir/app/utils/code-snippet.ngfactory.ts":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a", function() { return RenderType_CodeSnippet; });
/* harmony export (immutable) */ __webpack_exports__["b"] = View_CodeSnippet_0;
/* unused harmony export View_CodeSnippet_Host_0 */
/* unused harmony export CodeSnippetNgFactory */
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__angular_core__ = __webpack_require__("../../../core/@angular/core.es5.js");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1_clarity_angular_code_syntax_highlight_syntax_highlight__ = __webpack_require__("../../../../clarity-angular/code/syntax-highlight/syntax-highlight.js");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2__angular_common__ = __webpack_require__("../../../common/@angular/common.es5.js");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_3__app_utils_code_snippet__ = __webpack_require__("../../../../../src/app/utils/code-snippet.ts");
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */




var styles_CodeSnippet = ['pre[_ngcontent-%COMP%] {\n            background: transparent;\n            padding: 12px;\n        }'];
var RenderType_CodeSnippet = __WEBPACK_IMPORTED_MODULE_0__angular_core__["_17" /* ɵcrt */]({ encapsulation: 0, styles: styles_CodeSnippet,
    data: {} });
function View_CodeSnippet_1(_l) {
    return __WEBPACK_IMPORTED_MODULE_0__angular_core__["_44" /* ɵvid */](0, [(_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_20" /* ɵeld */](0, null, null, 6, null, null, null, null, null, null, null)),
        (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_42" /* ɵted */](null, ['\n            '])), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_20" /* ɵeld */](0, null, null, 3, 'pre', [], null, null, null, null, null)), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_20" /* ɵeld */](0, null, null, 2, 'code', [], null, null, null, null, null)), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_18" /* ɵdid */](1064960, [[1, 4]], 0, __WEBPACK_IMPORTED_MODULE_1_clarity_angular_code_syntax_highlight_syntax_highlight__["a" /* CodeHighlight */], [__WEBPACK_IMPORTED_MODULE_0__angular_core__["p" /* ElementRef */],
            __WEBPACK_IMPORTED_MODULE_0__angular_core__["P" /* Renderer2 */]], { highlight: [0, 'highlight'] }, null), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_42" /* ɵted */](null, ['', ''])), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_42" /* ɵted */](null, ['\n        ']))], function (_ck, _v) {
        var _co = _v.component;
        var currVal_0 = ('language-' + _co.language);
        _ck(_v, 4, 0, currVal_0);
    }, function (_ck, _v) {
        var _co = _v.component;
        var currVal_1 = _co.code.trim();
        _ck(_v, 5, 0, currVal_1);
    });
}
function View_CodeSnippet_2(_l) {
    return __WEBPACK_IMPORTED_MODULE_0__angular_core__["_44" /* ɵvid */](0, [(_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_20" /* ɵeld */](0, null, null, 5, null, null, null, null, null, null, null)),
        (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_42" /* ɵted */](null, ['\n            '])), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_20" /* ɵeld */](0, null, null, 2, 'pre', [], null, null, null, null, null)), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_20" /* ɵeld */](0, null, null, 1, 'code', [['class', 'clr-code']], null, null, null, null, null)), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_42" /* ɵted */](null, ['', ''])), (_l()(),
            __WEBPACK_IMPORTED_MODULE_0__angular_core__["_42" /* ɵted */](null, ['\n        ']))], null, function (_ck, _v) {
        var _co = _v.component;
        var currVal_0 = _co.code.trim();
        _ck(_v, 4, 0, currVal_0);
    });
}
function View_CodeSnippet_0(_l) {
    return __WEBPACK_IMPORTED_MODULE_0__angular_core__["_44" /* ɵvid */](0, [__WEBPACK_IMPORTED_MODULE_0__angular_core__["_40" /* ɵqud */](671088640, 1, { codeHighlight: 0 }), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_42" /* ɵted */](null, ['\n        '])), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_14" /* ɵand */](16777216, null, null, 1, null, View_CodeSnippet_1)), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_18" /* ɵdid */](16384, null, 0, __WEBPACK_IMPORTED_MODULE_2__angular_common__["k" /* NgIf */], [__WEBPACK_IMPORTED_MODULE_0__angular_core__["_2" /* ViewContainerRef */],
            __WEBPACK_IMPORTED_MODULE_0__angular_core__["Y" /* TemplateRef */]], { ngIf: [0, 'ngIf'] }, null), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_42" /* ɵted */](null, ['\n        '])), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_14" /* ɵand */](16777216, null, null, 1, null, View_CodeSnippet_2)), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_18" /* ɵdid */](16384, null, 0, __WEBPACK_IMPORTED_MODULE_2__angular_common__["k" /* NgIf */], [__WEBPACK_IMPORTED_MODULE_0__angular_core__["_2" /* ViewContainerRef */],
            __WEBPACK_IMPORTED_MODULE_0__angular_core__["Y" /* TemplateRef */]], { ngIf: [0, 'ngIf'] }, null), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_42" /* ɵted */](null, ['\n    ']))], function (_ck, _v) {
        var _co = _v.component;
        var currVal_0 = !_co.disablePrism;
        _ck(_v, 3, 0, currVal_0);
        var currVal_1 = _co.disablePrism;
        _ck(_v, 6, 0, currVal_1);
    }, null);
}
function View_CodeSnippet_Host_0(_l) {
    return __WEBPACK_IMPORTED_MODULE_0__angular_core__["_44" /* ɵvid */](0, [(_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_20" /* ɵeld */](0, null, null, 1, 'clr-code-snippet', [], null, null, null, View_CodeSnippet_0, RenderType_CodeSnippet)),
        __WEBPACK_IMPORTED_MODULE_0__angular_core__["_18" /* ɵdid */](4243456, null, 0, __WEBPACK_IMPORTED_MODULE_3__app_utils_code_snippet__["a" /* CodeSnippet */], [], null, null)], null, null);
}
var CodeSnippetNgFactory = __WEBPACK_IMPORTED_MODULE_0__angular_core__["_15" /* ɵccf */]('clr-code-snippet', __WEBPACK_IMPORTED_MODULE_3__app_utils_code_snippet__["a" /* CodeSnippet */], View_CodeSnippet_Host_0, { code: 'clrCode', language: 'clrLanguage',
    disablePrism: 'clrDisablePrism' }, {}, []);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FidXJrZS9SZXBvc2l0b3JpZXMvcG93ZXJuc3guZ2l0aHViLmlvL3NyYy9hcHAvdXRpbHMvY29kZS1zbmlwcGV0Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2FidXJrZS9SZXBvc2l0b3JpZXMvcG93ZXJuc3guZ2l0aHViLmlvL3NyYy9hcHAvdXRpbHMvY29kZS1zbmlwcGV0LnRzIiwibmc6Ly8vVXNlcnMvYWJ1cmtlL1JlcG9zaXRvcmllcy9wb3dlcm5zeC5naXRodWIuaW8vc3JjL2FwcC91dGlscy9jb2RlLXNuaXBwZXQudHMuQ29kZVNuaXBwZXQuaHRtbCIsIm5nOi8vL1VzZXJzL2FidXJrZS9SZXBvc2l0b3JpZXMvcG93ZXJuc3guZ2l0aHViLmlvL3NyYy9hcHAvdXRpbHMvY29kZS1zbmlwcGV0LnRzLkNvZGVTbmlwcGV0X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgICAgIDxuZy1jb250YWluZXIgKm5nSWY9XCIhZGlzYWJsZVByaXNtXCI+XG4gICAgICAgICAgICA8cHJlPjxjb2RlIFtjbHItY29kZS1oaWdobGlnaHRdPVwiJ2xhbmd1YWdlLScrbGFuZ3VhZ2VcIj57e2NvZGUudHJpbSgpfX08L2NvZGU+PC9wcmU+XG4gICAgICAgIDwvbmctY29udGFpbmVyPlxuICAgICAgICA8bmctY29udGFpbmVyICpuZ0lmPVwiZGlzYWJsZVByaXNtXCI+XG4gICAgICAgICAgICA8cHJlPjxjb2RlIGNsYXNzPVwiY2xyLWNvZGVcIj57e2NvZGUudHJpbSgpfX08L2NvZGU+PC9wcmU+XG4gICAgICAgIDwvbmctY29udGFpbmVyPlxuICAgICIsIjxjbHItY29kZS1zbmlwcGV0PjwvY2xyLWNvZGUtc25pcHBldD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7O29CQ0NRO01BQUE7TUFBb0MsbURBQ2hDO1VBQUE7VUFBQSw4QkFBSztVQUFBO1VBQUEsdUJBQUE7c0JBQUEsNkNBQWtEO1VBQUEsVUFBNEI7O0lBQXhFO0lBQU4sV0FBTSxTQUFOOzs7SUFBa0Q7SUFBQTs7OztvQkFFM0Q7TUFBQTtNQUFtQyxtREFDL0I7VUFBQTtVQUFBLDhCQUFLO1VBQUE7VUFBQSw4QkFBdUIsd0NBQTRCO2lCQUFBOztJQUE1QjtJQUFBOzs7OzJEQUx4QztNQUFBLGlCQUNRO01BQUEsNEJBQUE7b0JBQUEsbUNBRWU7TUFBQSxpQkFDZjtNQUFBLDRCQUFBO29CQUFBLG1DQUVlO01BQUE7O0lBTEQ7SUFBZCxXQUFjLFNBQWQ7SUFHYztJQUFkLFdBQWMsU0FBZDs7OztvQkNKUjtNQUFBO2FBQUE7Ozs7OyJ9
//# sourceMappingURL=/Users/aburke/Repositories/powernsx.github.io/src/code-snippet.ngfactory.js.map

/***/ }),

/***/ "../../../../../src/app/utils/code-snippet.ts":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a", function() { return CodeSnippet; });
var CodeSnippet = (function () {
    function CodeSnippet() {
        this.language = "html";
        this.disablePrism = false;
    }
    CodeSnippet.prototype.ngAfterViewInit = function () {
        if (this.codeHighlight) {
            this.codeHighlight.redraw();
        }
    };
    return CodeSnippet;
}());

//# sourceMappingURL=/Users/aburke/Repositories/powernsx.github.io/src/code-snippet.js.map

/***/ }),

/***/ "../../../../../src/app/utils/hash-listener.directive.ts":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a", function() { return HashListener; });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__angular_router__ = __webpack_require__("../../../router/@angular/router.es5.js");
/*
 * Hack while waiting for https://github.com/angular/angular/issues/6595 to be fixed.
 */

var HashListener = (function () {
    function HashListener(route) {
        var _this = this;
        this.route = route;
        this.sub = this.route.fragment.subscribe(function (f) {
            _this.scrollToAnchor(f, false);
        });
    }
    HashListener.prototype.ngOnInit = function () {
        this.scrollToAnchor(this.route.snapshot.fragment, false);
    };
    HashListener.prototype.scrollToAnchor = function (hash, smooth) {
        if (smooth === void 0) { smooth = true; }
        if (hash) {
            var element = document.querySelector("#" + hash);
            if (element) {
                element.scrollIntoView({
                    behavior: smooth ? "smooth" : "instant",
                    block: "start"
                });
            }
        }
    };
    HashListener.prototype.ngOnDestroy = function () {
        this.sub.unsubscribe();
    };
    HashListener.ctorParameters = function () { return [{ type: __WEBPACK_IMPORTED_MODULE_0__angular_router__["a" /* ActivatedRoute */] }]; };
    return HashListener;
}());

//# sourceMappingURL=/Users/aburke/Repositories/powernsx.github.io/src/hash-listener.directive.js.map

/***/ }),

/***/ "../../../../../src/app/utils/scrollspy.directive.ts":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a", function() { return ScrollSpy; });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__angular_core__ = __webpack_require__("../../../core/@angular/core.es5.js");
/*
 * Hack while waiting for https://github.com/angular/angular/issues/6595 to be fixed.
 */

var ScrollSpy = (function () {
    function ScrollSpy(renderer) {
        this.renderer = renderer;
        this.anchors = [];
        this.throttle = false;
    }
    Object.defineProperty(ScrollSpy.prototype, "links", {
        set: function (routerLinks) {
            var _this = this;
            this.anchors = routerLinks.map(function (routerLink) { return "#" + routerLink.fragment; });
            this.sub = routerLinks.changes.subscribe(function () {
                _this.anchors = routerLinks.map(function (routerLink) { return "#" + routerLink.fragment; });
            });
        },
        enumerable: true,
        configurable: true
    });
    ScrollSpy.prototype.handleEvent = function () {
        var _this = this;
        this.scrollPosition = this.scrollable.scrollTop;
        if (!this.throttle) {
            window.requestAnimationFrame(function () {
                var currentLinkIndex = _this.findCurrentAnchor() || 0;
                _this.linkElements.forEach(function (link, index) {
                    _this.renderer.setElementClass(link.nativeElement, "active", index === currentLinkIndex);
                });
                _this.throttle = false;
            });
        }
        this.throttle = true;
    };
    ScrollSpy.prototype.findCurrentAnchor = function () {
        for (var i = this.anchors.length - 1; i >= 0; i--) {
            var anchor = this.anchors[i];
            if (this.scrollable.querySelector(anchor) && this.scrollable.querySelector(anchor).offsetTop <= this.scrollPosition) {
                return i;
            }
        }
    };
    ScrollSpy.prototype.ngOnInit = function () {
        this.scrollable.addEventListener("scroll", this);
    };
    ScrollSpy.prototype.ngOnDestroy = function () {
        this.scrollable.removeEventListener("scroll", this);
        if (this.sub) {
            this.sub.unsubscribe();
        }
    };
    ScrollSpy.ctorParameters = function () { return [{ type: __WEBPACK_IMPORTED_MODULE_0__angular_core__["O" /* Renderer */] }]; };
    return ScrollSpy;
}());

//# sourceMappingURL=/Users/aburke/Repositories/powernsx.github.io/src/scrollspy.directive.js.map

/***/ })

});